"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['CardiacMap.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    name="cardiacmap",
    version="0.1.0",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    description="Cardiac Optical Mapper",
    packages=['cardiacmap']
)
